# Generated by Django 4.2.5 on 2023-11-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Media'), ('D', 'Difícil')], max_length=1)),
                ('descripcion', models.TextField()),
                ('ingredientes', models.ManyToManyField(to='core.ingredientes')),
            ],
        ),
        migrations.CreateModel(
            name='MiRecetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
    ]
