# Generated by Django 4.2.5 on 2023-10-23 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='MiRecetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('dificultad', models.CharField(choices=[('F', 'Fácil'), ('M', 'Media'), ('D', 'Difícil')], max_length=1)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteMedido',
            fields=[
                ('ingredientes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.ingredientes')),
                ('unidad_de_medida', models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('CS', 'Cucharada sopera'), ('CC', 'Cucharadita de postre'), ('ML', 'Mililitro')], max_length=2)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
            ],
            bases=('core.ingredientes',),
        ),
        migrations.CreateModel(
            name='Organizador_Semanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2)),
                ('periodo', models.CharField(choices=[('AL', 'Almuerzo'), ('CE', 'Cena')], max_length=2)),
                ('recetas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.receta')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(to='core.ingredientemedido'),
        ),
    ]
