# Generated by Django 4.2.7 on 2023-11-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientemedido',
            name='unidad_de_medida',
            field=models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('Cu', 'Cucharada'), ('CS', 'Cucharada sopera'), ('CC', 'Cucharadita de postre'), ('VA', 'Vaso'), ('ML', 'Mililitro'), ('UN', 'Unidad')], max_length=2),
        ),
    ]
