# Generated by Django 4.2.7 on 2023-11-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
    ]
